# Generated by Django 3.1.2 on 2020-11-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbourhood', '0003_auto_20201104_1309'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='article',
            new_name='post',
        ),
    ]
